name: Firebase Web CI

on:
  push:
    branches:
      - master
      - develop
      - "feature/**"
      - "release/**"

jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    env:
      CI_FIREBASE_MESSAGE: ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.url }}/checks

    steps:
      ## Checkout current branch
      - uses: actions/checkout@v1

      ## Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Install dependencies
      - name: yarn install
        run: |
          yarn

      ## Test
      - name: Run tests
        run: |
          CI=true yarn test

      ## Build & Deploy Dev
      - name: Build & Deploy Dev
        if: contains(github.ref, 'refs/heads/feature/') || github.ref == 'refs/heads/develop'
        run: |
          yarn build
          yarn firebase deploy --only hosting -P development --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"

      ## Build & Deploy Staging
      - name: Build & Deploy Staging
        if: contains(github.ref, 'refs/heads/release/')
        run: |
          yarn build
          yarn firebase deploy --only hosting -P staging --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"

      ## Build & Deploy Production
      - name: Build & Deploy Production
        if: github.ref == 'refs/heads/master'
        run: |
          yarn build
          yarn firebase deploy --only hosting -P production --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"